apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: private-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: private-api
    spec:
      containers:
      - name: private-api
        image: radumatei/private-api
        ports:
            - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: private-api-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: private-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
